# Generated by Django 4.1.7 on 2023-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_regpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=122)),
                ('mobileno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='regpage',
        ),
    ]
