# Generated by Django 4.1.7 on 2023-03-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_register_delete_regpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='mobileno',
            new_name='MOBILENO',
        ),
    ]
