# Generated by Django 4.1.7 on 2023-03-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_email_register_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='EMAIL',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='MOBILENO',
            new_name='mobileno',
        ),
    ]
